namespace RGLUnityPlugin
{
public enum RGLNodeType
	{
		UNKNOWN = -1,
		RAYS_FROM_MAT3X4F = 1,
		RAYS_SET_RING_IDS,
		RAYS_TRANSFORM,
		POINTS_TRANSFORM,
		POINTS_FORMAT,
		POINTS_YIELD,
		POINTS_COMPACT,
		POINTS_DOWNSAMPLE,
		POINTS_WRITE_PCD_FILE,
		RAYTRACE,
	};
}