name: Feature request
description: request a feature
body:
  - type: checkboxes
    attributes:
      label: Checklist
      description: Confirm the following items before proceeding.
      options:
        - label: I've read the [contribution guidelines](https://tier4.github.io/AWSIM/DeveloperGuide/HowToContribute/).
          required: true
        - label: I've searched other issues and no duplicate issues were found.
          required: true

  - type: textarea
    attributes:
      label: Description
      description: Write a brief description of the task.
    validations:
      required: true
