// Copyright 2025 TIER IV, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: autoware_vehicle_msgs.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace AutowareVehicleMsgs {

  /// <summary>Holder for reflection information generated from autoware_vehicle_msgs.proto</summary>
  public static partial class AutowareVehicleMsgsReflection {

    #region Descriptor
    /// <summary>File descriptor for autoware_vehicle_msgs.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AutowareVehicleMsgsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChthdXRvd2FyZV92ZWhpY2xlX21zZ3MucHJvdG8SFWF1dG93YXJlX3ZlaGlj",
            "bGVfbXNncxoYYnVpbHRpbl9pbnRlcmZhY2VzLnByb3RvInUKC0dlYXJDb21t",
            "YW5kEicKBXN0YW1wGAEgASgLMhguYnVpbHRpbl9pbnRlcmZhY2VzLlRpbWUS",
            "PQoHY29tbWFuZBgCIAEoDjIsLmF1dG93YXJlX3ZlaGljbGVfbXNncy5HZWFy",
            "Q29tbWFuZF9Db25zdGFudHMq2QIKFUdlYXJDb21tYW5kX0NvbnN0YW50cxII",
            "CgROT05FEAASCwoHTkVVVFJBTBABEgkKBURSSVZFEAISCwoHRFJJVkVfMhAD",
            "EgsKB0RSSVZFXzMQBBILCgdEUklWRV80EAUSCwoHRFJJVkVfNRAGEgsKB0RS",
            "SVZFXzYQBxILCgdEUklWRV83EAgSCwoHRFJJVkVfOBAJEgsKB0RSSVZFXzkQ",
            "ChIMCghEUklWRV8xMBALEgwKCERSSVZFXzExEAwSDAoIRFJJVkVfMTIQDRIM",
            "CghEUklWRV8xMxAOEgwKCERSSVZFXzE0EA8SDAoIRFJJVkVfMTUQEBIMCghE",
            "UklWRV8xNhAREgwKCERSSVZFXzE3EBISDAoIRFJJVkVfMTgQExILCgdSRVZF",
            "UlNFEBQSDQoJUkVWRVJTRV8yEBUSCAoEUEFSSxAWEgcKA0xPVxAXEgkKBUxP",
            "V18yEBhiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::BuiltinInterfaces.BuiltinInterfacesReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::AutowareVehicleMsgs.GearCommand_Constants), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::AutowareVehicleMsgs.GearCommand), global::AutowareVehicleMsgs.GearCommand.Parser, new[]{ "Stamp", "Command" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum GearCommand_Constants {
    [pbr::OriginalName("NONE")] None = 0,
    [pbr::OriginalName("NEUTRAL")] Neutral = 1,
    [pbr::OriginalName("DRIVE")] Drive = 2,
    [pbr::OriginalName("DRIVE_2")] Drive2 = 3,
    [pbr::OriginalName("DRIVE_3")] Drive3 = 4,
    [pbr::OriginalName("DRIVE_4")] Drive4 = 5,
    [pbr::OriginalName("DRIVE_5")] Drive5 = 6,
    [pbr::OriginalName("DRIVE_6")] Drive6 = 7,
    [pbr::OriginalName("DRIVE_7")] Drive7 = 8,
    [pbr::OriginalName("DRIVE_8")] Drive8 = 9,
    [pbr::OriginalName("DRIVE_9")] Drive9 = 10,
    [pbr::OriginalName("DRIVE_10")] Drive10 = 11,
    [pbr::OriginalName("DRIVE_11")] Drive11 = 12,
    [pbr::OriginalName("DRIVE_12")] Drive12 = 13,
    [pbr::OriginalName("DRIVE_13")] Drive13 = 14,
    [pbr::OriginalName("DRIVE_14")] Drive14 = 15,
    [pbr::OriginalName("DRIVE_15")] Drive15 = 16,
    [pbr::OriginalName("DRIVE_16")] Drive16 = 17,
    [pbr::OriginalName("DRIVE_17")] Drive17 = 18,
    [pbr::OriginalName("DRIVE_18")] Drive18 = 19,
    [pbr::OriginalName("REVERSE")] Reverse = 20,
    [pbr::OriginalName("REVERSE_2")] Reverse2 = 21,
    [pbr::OriginalName("PARK")] Park = 22,
    [pbr::OriginalName("LOW")] Low = 23,
    [pbr::OriginalName("LOW_2")] Low2 = 24,
  }

  #endregion

  #region Messages
  public sealed partial class GearCommand : pb::IMessage<GearCommand> {
    private static readonly pb::MessageParser<GearCommand> _parser = new pb::MessageParser<GearCommand>(() => new GearCommand());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GearCommand> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AutowareVehicleMsgs.AutowareVehicleMsgsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GearCommand() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GearCommand(GearCommand other) : this() {
      stamp_ = other.stamp_ != null ? other.stamp_.Clone() : null;
      command_ = other.command_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GearCommand Clone() {
      return new GearCommand(this);
    }

    /// <summary>Field number for the "stamp" field.</summary>
    public const int StampFieldNumber = 1;
    private global::BuiltinInterfaces.Time stamp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::BuiltinInterfaces.Time Stamp {
      get { return stamp_; }
      set {
        stamp_ = value;
      }
    }

    /// <summary>Field number for the "command" field.</summary>
    public const int CommandFieldNumber = 2;
    private global::AutowareVehicleMsgs.GearCommand_Constants command_ = global::AutowareVehicleMsgs.GearCommand_Constants.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::AutowareVehicleMsgs.GearCommand_Constants Command {
      get { return command_; }
      set {
        command_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GearCommand);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GearCommand other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Stamp, other.Stamp)) return false;
      if (Command != other.Command) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (stamp_ != null) hash ^= Stamp.GetHashCode();
      if (Command != global::AutowareVehicleMsgs.GearCommand_Constants.None) hash ^= Command.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (stamp_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Stamp);
      }
      if (Command != global::AutowareVehicleMsgs.GearCommand_Constants.None) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Command);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (stamp_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Stamp);
      }
      if (Command != global::AutowareVehicleMsgs.GearCommand_Constants.None) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Command);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GearCommand other) {
      if (other == null) {
        return;
      }
      if (other.stamp_ != null) {
        if (stamp_ == null) {
          Stamp = new global::BuiltinInterfaces.Time();
        }
        Stamp.MergeFrom(other.Stamp);
      }
      if (other.Command != global::AutowareVehicleMsgs.GearCommand_Constants.None) {
        Command = other.Command;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (stamp_ == null) {
              Stamp = new global::BuiltinInterfaces.Time();
            }
            input.ReadMessage(Stamp);
            break;
          }
          case 16: {
            Command = (global::AutowareVehicleMsgs.GearCommand_Constants) input.ReadEnum();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
